### PR TITLE
Add dockerfile and totally use new docker images

### PR DESCRIPTION
**Pull request by xingweitian**
These two docker images have been built and pushed to docker hub.

- https://hub.docker.com/r/xingweitian/ubuntu-for-cfi-jdk8
- https://hub.docker.com/r/xingweitian/ubuntu-for-cfi-jdk11

Python3 is used in these images.

We need another two PRs to update CF and CFI to pull these newest docker images when running on travis. When they are ready, opprop/do-like-javac#15 should also be merged.

---

Here is the reversed dockerfile from charles's docker image:
```dockerfile
RUN /bin/sh -c apt-get -qqy update \
    && apt-get -qqy install   ant   binutils   build-essential   cpp   git   gradle   libcurl3-gnutls   make   maven   mercurial   unzip   wget   default-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN /bin/sh -c apt-get -qqy update \
    && apt-get -qqy install python
RUN /bin/sh -c apt-get -qqy update \
    && apt-get -qqy install python-pip
RUN /bin/sh -c export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
RUN /bin/sh -c pip install --upgrade pip \
    && pip install PyGithub   pyyaml   subprocess32   lithium

```

~~I did some improvement according to the dockerfiles in typetools/CF. Some unnecessary python packages have been removed, e.g., `pygithub`, `pyyaml` and `subprocess32`.~~
~~- I did not see any use of `pygithub` and `pyyaml` in do-like-javac, I think they are used to debug something in the docker container.~~
- In python3, we use `subprocess` instead of `subprocess32`.

I found that `pygithub` and `pyyaml` are used by `unit-inference`, so I added them into Dockerfiles agagin.

### CODE REVIEW

**Comment by xingweitian** [comment]
For this PR, we need to think about how to organize the docker images, how many images do we need? Do we need `11-plus`, `8-plus`?

**Comment by wmdietl** [comment]
Following up on #106 can you see what made these docker images slow?

**Comment by xingweitian** [comment]
> Following up on #106 can you see what made these docker images slow?

Sure, no problem.

**Comment by xingweitian** [comment]
@wmdietl I updated my docker images and now they work properly.

In the past, my docker images are based on `mdernst/ubuntu-for-cf-jdk8` and `mdernst/ubuntu-for-cf-jdk11`, and now they are dependent on `mdernst/cf-ubuntu-jdk8` and `mdernst/cf-ubuntu-jdk11`. After changing this, everything works...

I did not find a huge difference between `ubuntu-for-cf-jdk` and `cf-ubuntu-jdk`, it is still not clear to me why my docker images are working good now...

**Comment by xingweitian** [comment]
Now all the docker images are from my docker hub repo, we are not using docker images from typetools anymore.

**Comment by xingweitian** [comment]
@wmdietl This PR is ready for code review.

**Pull request merged**
