### PR TITLE
Global java reformat

### PR DESCRIPTION
**Pull request by d367wang**
(i) run reformatting under jdk11  
(ii) adapt expected error message based on the reformatting  
(iii) remove `misc_jdk8` in azure-pipelines   
(iv) adapt `checker/bin-devel/git.pre-commit`

### CODE REVIEW

**Comment by wmdietl** [comment]
Thanks for doing this! Some of the tests are failing because of changed line numbers. Could you touch up https://github.com/opprop/checker-framework/blob/master/framework/jtreg/StubParserEnum/WithoutStub.out and any other test files that contain line numbers?

We can ignore the missing javadoc messages in `misc_jdk11`.

Do you understand why the `misc_jdk8` tests are still failing with `Improper formatting` errors?

**Comment by d367wang** [comment]
The issue is due to the out-of-date local cache of `run-google-java-format`, not a CF issue.

**Comment by xingweitian** [comment]
> The issue is due to the out-of-date local cache of `run-google-java-format`, not a CF issue.

Do we know how to update this cache?

**Comment by d367wang** [comment]
> > The issue is due to the out-of-date local cache of `run-google-java-format`, not a CF issue.
> 
> Do we know how to update this cache?

It should have pulled changes to update the cache, according to https://github.com/opprop/checker-framework/blob/3f6178b946227de9b14291ba7a71aba92a6961c7/build.gradle#L450
But it seems not working for me. I resolved this by removing the cache and run reformatting so it clone the up-to-date version from the remote.

**Review by wmdietl — APPROVED** [review]
Thanks!

**Pull request merged**
