### PR TITLE
Targetlocation

### PR DESCRIPTION
**Pull request by topnessman**
Enforce TargetLocations meta-annotation
Problems still exist:
Javac implementation doesn't use same separate trees to represent one part of code.
Example:
Object o =  new @1 Object();// We use VariableTree and NewClassTree
Object l = (@2 Object) o;// We only use VariableTree, but no TypeCastTree, which causes inconsistency while reporting errors.
I think we might need to change the behavior of Visitor or Compiler a bit.

### CODE REVIEW

**Comment by wmdietl** [comment]
Hi Mier, thanks for wrapping up work on this!
The description should mention that this is two changes: add the TYPE_DECLARATION default location and validate TargetLocations. Can these be separated into two pull requests?

Can you see why the travis tests are failing and get them working?

**Comment by topnessman** [comment]
@wmdietl  How can I get only the explicitly written annotations on a tree,i.e. ClassTree, VariableTree, MethodTree(return type), ExpressionTree without inherited annotations or computed annotations(eg. defaults)? Because LocationValidator  only validates explicit annotations. If we use atf.getAnnotatedType(tree) all the other annotations will be mixed in.

**Comment by wmdietl** [comment]
@topnessman Why should only explicit annotations be validated? If defaulted annotations violate the LocationValidator, something is wrong with the defaults.

**Comment by topnessman** [comment]
@wmdietl TargetLocations meta-annotation's documentation says:
 * A meta-annotation that restricts the type-use locations where a type
 * qualifier may be written
This enables a type system designer to permit a qualifier to be written
 * only in certain locations.
Clearly, TargetLocations only enforces explicitly written annotations, i.e. emit errors when programmer explicitly write an annotation on a location not specified by its TargetLocations meta-annotation.
For defaults, we don't enforce that. Even if we default an annotation on a location which is not specified in its TargetLocations meta-annotation, we DON'T emit errors. This is consistent with the documentation: we are only specifying which annotations can be written on certain locations, but not specifying which annotations can be used on certain locations(includes explicit, defaults, inherited)
So every enforcement of TargetLocations should happen only on explicit annotations.

**Comment by topnessman** [comment]
@wmdietl I think this confuse is caused by the confusing name: TargetLocations. I think we need a better name for it, like AllowedWrittenLocations

**Comment by wmdietl** [comment]
@topnessman There is no easy way to determine whether an annotation on an ATM was added because the user explicitly wrote it or because it was defaulted.
So the enforcement of TargetLocations needs to run before defaulting is run. Can you see whether there is a nice way of doing that?

**Comment by topnessman** [comment]
@wmdietl We might need a discussion, because my solution will invoke TypeFromTree utility class, which is deprecated to be used outsite ATF.

**Pull request closed without merging**
