### PR TITLE
Make travis pass

### PR DESCRIPTION
**Pull request by xingweitian**
This PR
1. update .travis.yml to make test group `misc` pass on travis. 
2. try to make test group `cfi` pass on travis.

### CODE REVIEW

**Comment by xingweitian** [comment]
I resolve [Unmappable character for encoding ASCII error](https://travis-ci.org/opprop/checker-framework/jobs/573264090#L1550) by adding `export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` in `checker/bin-devel/test-cf-inference.sh`. It works but I am not sure if there is a better way to solve this.

**Comment by wmdietl** [comment]
I would suggest changing that line from

```
// "↧" sign is \u21A7
```

to something like

```
// `\u21A7` is a downward arrow symbol
```

Please undo adding the extra `JAVA_TOOL_OPTIONS`.

**Comment by xingweitian** [comment]
> I would suggest changing that line from
> 
> ```
> // "↧" sign is \u21A7
> ```
> 
> to something like
> 
> ```
> // `\u21A7` is a downward arrow symbol
> ```
> 
> Please undo adding the extra `JAVA_TOOL_OPTIONS`.

Since #93 has already been merged, I will create a new PR to reset this and update the comment.

**Comment by wmdietl** [comment]
Well, #94 was already merged.
In general, we squash PRs to produce a single commit in master.
We don't squash the update PRs, to have the same commits as typetools/master. As #94 was already in the update PR, and I didn't want to start a fresh PR, I think it's fine to have a separate PR to undo the change here and to rewrite that comment in CFI.
Thanks for your work on these issues!

**Comment by xingweitian** [comment]
> Well, #94 was already merged.
> In general, we squash PRs to produce a single commit in master.
> We don't squash the update PRs, to have the same commits as typetools/master. As #94 was already in the update PR, and I didn't want to start a fresh PR, I think it's fine to have a separate PR to undo the change here and to rewrite that comment in CFI.
> Thanks for your work on these issues!

If I understand correctly, I will create a new PR in CF to undo the change about `JAVA_TOOL_OPTIONS`. And also, another new PR in CFI to update the comment. I will do CFI at first to make sure that we can pass travis.

**Comment by wmdietl** [comment]
Yes, that sounds good.

**Pull request merged**
