### PR TITLE
Set var arg type before calling `viewpointAdaptConstructor`

### PR DESCRIPTION
**Pull request by aosen-xiong**

### CODE REVIEW

**Comment by wmdietl** [comment]
Wouldn't it be easier to pull in all changes in eisop instead of cherry-picking a few?

**Comment by aosen-xiong** [comment]
> Wouldn't it be easier to pull in all changes in eisop instead of cherry-picking a few?

@wmdietl Should we do it right now? I thought we are supposed pull in the change by release.

**Comment by wmdietl** [comment]
> @wmdietl Should we do it right now? I thought we are supposed pull in the change by release.

Pulling in all changes up to a certain date seems less error prone than just pulling in certain commits.
With this approach, how do you know whether this change depended on some earlier changes or not?
Usually, just waiting for the next release should be enough, with the exception of maybe #268, as the updates to `plume-scripts` broke this repository.

**Comment by aosen-xiong** [comment]
> > @wmdietl Should we do it right now? I thought we are supposed pull in the change by release.
> 
> Pulling in all changes up to a certain date seems less error prone than just pulling in certain commits. With this approach, how do you know whether this change depended on some earlier changes or not? Usually, just waiting for the next release should be enough, with the exception of maybe #268, as the updates to `plume-scripts` broke this repository.

Okay, I will wait until changes related to viewpointadpatation PRs have been merged. In that case, we can have less PICO crashed .

**Pull request closed without merging**
