### PR TITLE
Opprop upstream update 11 13 2017

### PR DESCRIPTION
**Pull request by jyluo**

### CODE REVIEW

**Comment by CharlesZ-Chen** [comment]
Downstream test failed due to CFI out-date with CF changes in this upstream update.

https://github.com/opprop/checker-framework-inference/pull/107 is expected to fix this travis failure.

**Comment by CharlesZ-Chen** [comment]
Mier, It sees this PR still not finish the travis test...

**Comment by topnessman** [comment]
Oh oh, I didn't notice this. I just pushed the latest CF from typetools to opprop. I'll revert it back.

**Comment by CharlesZ-Chen** [comment]
No problem. Let's just wait to see if the travis passed. If it passed, then we don't need to revert.

**Comment by topnessman** [comment]
Sure.

**Comment by topnessman** [comment]
Looks like the test has passed?

**Comment by CharlesZ-Chen** [comment]
Yes. All good now.

**Pull request merged**
