### PR TITLE
Update from typetools 2020-04-23

### PR DESCRIPTION
**Pull request by xingweitian**
Today typetools released version 3.3.0. We need a regular update.

### CODE REVIEW

**Comment by xingweitian** [comment]
It can be merged after https://github.com/typetools/checker-framework/issues/3223 is solved.

**Comment by wmdietl** [comment]
@xingweitian All tests are passing, so can we merge this?
Or is there anything we should discuss?

**Comment by xingweitian** [comment]
> @xingweitian All tests are passing, so can we merge this?
> Or is there anything we should discuss?

The corresponding PR in checker-framework-inference had some issues with jdk11. I don't know why there are `out of memory` errors in jdk11.

**Comment by wmdietl** [comment]
> > @xingweitian All tests are passing, so can we merge this?
> > Or is there anything we should discuss?
> 
> The corresponding PR in checker-framework-inference had some issues with jdk11. I don't know why there are `out of memory` errors in jdk11.

Thanks! Why are the tests green here if downstream is failing?
Are they running inconsistent test suites?
Or is it a random failure that disappears when re-running?

**Comment by xingweitian** [comment]
> > > @xingweitian All tests are passing, so can we merge this?
> > > Or is there anything we should discuss?
> > 
> > 
> > The corresponding PR in checker-framework-inference had some issues with jdk11. I don't know why there are `out of memory` errors in jdk11.
> 
> Thanks! Why are the tests green here if downstream is failing?
> Are they running inconsistent test suites?
> Or is it a random failure that disappears when re-running?

We did not run `cfi-jdk11` test on Travis now (Inconsistent with Azure pipelines).
https://github.com/typetools/checker-framework/blob/master/.travis.yml#L29
That's why the tests green. It looks like this is also an issue in typetools.

**Comment by xingweitian** [comment]
But `cfi-jdk11` in typetools can pass Azure piplines. Should we also change to Azure pipelines?

**Comment by wmdietl** [comment]
I've opened https://github.com/typetools/checker-framework/pull/3256 to see whether it works on travis. I don't expect that to be the issue.
It might be how we read JDK stub files in 11:
https://github.com/opprop/checker-framework-inference/pull/263#issuecomment-613672016

**Pull request merged**
